spring:
  datasource:
    url: jdbc:h2:mem:db;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.scripts.create-target: create.sql
#      javax.persistence.schema-generation.scripts.create-source: metadata
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
