create table challenge_slot (id bigint generated by default as identity, end_time timestamp, start_time timestamp, booked_by bigint, owner_id bigint not null, primary key (id));
create table challenge_user (id bigint generated by default as identity, username varchar(255), primary key (id));
alter table challenge_slot add constraint UKsmcwx3f0yttnnmlfjtbtq42uq unique (start_time, owner_id);
alter table challenge_user add constraint UKd90ko45fbod62cccenxyboqbq unique (username);
alter table challenge_slot add constraint FKqxmukm33n3b4g1lka3g4mon6m foreign key (booked_by) references challenge_user;
alter table challenge_slot add constraint FKmb5cf0b8bjifl9uhe0mi4lyyw foreign key (owner_id) references challenge_user;
